import type { Skill } from "@/types/skill";

// 默认 skills 数据，当 API 超时时使用
export const DEFAULT_SKILLS: Skill[] = [
  {
    id: "anthropics-skills",
    name: "skills",
    description: "Public repository for Agent Skills - Official Anthropic examples",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills",
    stars: 500,
    category: "dev-tools",
    tags: ["claude-skills", "official", "examples"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "travisvn-awesome-claude-skills",
    name: "awesome-claude-skills",
    description: "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows",
    author: "travisvn",
    repo_url: "https://github.com/travisvn/awesome-claude-skills",
    stars: 450,
    category: "other",
    tags: ["awesome-list", "claude-skills", "resources"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "alirezarezvani-claude-skills",
    name: "claude-skills",
    description: "53+ domain expert skills including /brainstorm, /write-plan, /execute-plan commands",
    author: "alirezarezvani",
    repo_url: "https://github.com/alirezarezvani/claude-skills",
    stars: 400,
    category: "productivity",
    tags: ["claude-skills", "productivity", "planning"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "daymade-claude-code-skills",
    name: "claude-code-skills",
    description: "Professional Claude Code skills marketplace featuring production-ready skills for enhanced development workflows",
    author: "daymade",
    repo_url: "https://github.com/daymade/claude-code-skills",
    stars: 350,
    category: "dev-tools",
    tags: ["claude-code", "development", "marketplace"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "ComposioHQ-awesome-claude-skills",
    name: "awesome-claude-skills",
    description: "A curated list of awesome Claude Skills, resources, and tools for customizing Claude AI workflows",
    author: "ComposioHQ",
    repo_url: "https://github.com/ComposioHQ/awesome-claude-skills",
    stars: 300,
    category: "other",
    tags: ["awesome-list", "claude-skills", "composio"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "mhattingpete-claude-skills-marketplace",
    name: "claude-skills-marketplace",
    description: "Claude Code Skills for software engineering workflows - Git automation, testing, and code review",
    author: "mhattingpete",
    repo_url: "https://github.com/mhattingpete/claude-skills-marketplace",
    stars: 250,
    category: "dev-tools",
    tags: ["git", "testing", "code-review"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "VoltAgent-awesome-agent-skills",
    name: "awesome-agent-skills",
    description: "300+ Agent Skills compatible with Codex, Antigravity, Gemini CLI, Cursor and more",
    author: "VoltAgent",
    repo_url: "https://github.com/VoltAgent/awesome-agent-skills",
    stars: 200,
    category: "automation",
    tags: ["agent-skills", "multi-platform", "automation"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "libukai-awesome-agent-skills",
    name: "awesome-agent-skills",
    description: "Agent Skills 终极指南：快速入门、推荐技能、最新资讯 (Chinese)",
    author: "libukai",
    repo_url: "https://github.com/libukai/awesome-agent-skills",
    stars: 180,
    category: "other",
    tags: ["chinese", "guide", "agent-skills"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "netresearch-claude-code-marketplace",
    name: "claude-code-marketplace",
    description: "Curated Agent Skills collection for AI-assisted development by Netresearch",
    author: "netresearch",
    repo_url: "https://github.com/netresearch/claude-code-marketplace",
    stars: 150,
    category: "dev-tools",
    tags: ["marketplace", "curated", "development"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "affaan-m-everything-claude-code",
    name: "everything-claude-code",
    description: "Complete Claude Code configuration collection - agents, skills, hooks, commands, rules, MCPs (Anthropic Hackathon Winner)",
    author: "affaan-m",
    repo_url: "https://github.com/affaan-m/everything-claude-code",
    stars: 140,
    category: "dev-tools",
    tags: ["configuration", "hackathon-winner", "complete"],
    skill_md_url: "",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
];
