import type { Skill } from "@/types/skill";

// 默认 skills 数据 - 官方和高质量 skills
// 只包含真正有 SKILL.md 的可安装 skills
export const DEFAULT_SKILLS: Skill[] = [
  // ========== Anthropic Official Skills (16) ==========
  {
    id: "anthropics-docx",
    name: "docx",
    description: "Create, edit, and analyze Word documents",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/docx",
    stars: 1500,
    category: "productivity",
    tags: ["anthropics", "official", "document"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/docx/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-pdf",
    name: "pdf",
    description: "Extract text, create PDFs, and handle forms",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/pdf",
    stars: 1500,
    category: "productivity",
    tags: ["anthropics", "official", "pdf"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/pdf/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-xlsx",
    name: "xlsx",
    description: "Create, edit, and analyze Excel spreadsheets",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/xlsx",
    stars: 1500,
    category: "data",
    tags: ["anthropics", "official", "excel"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/xlsx/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-pptx",
    name: "pptx",
    description: "Create, edit, and analyze PowerPoint presentations",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/pptx",
    stars: 1500,
    category: "productivity",
    tags: ["anthropics", "official", "powerpoint"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/pptx/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-doc-coauthoring",
    name: "doc-coauthoring",
    description: "Collaborative document editing and co-authoring",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring",
    stars: 1500,
    category: "content",
    tags: ["anthropics", "official", "collaboration"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/doc-coauthoring/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-mcp-builder",
    name: "mcp-builder",
    description: "Create MCP servers to integrate external APIs and services",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/mcp-builder",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "mcp"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/mcp-builder/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-skill-creator",
    name: "skill-creator",
    description: "Guide for creating skills that extend Claude's capabilities",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "meta"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/skill-creator/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-webapp-testing",
    name: "webapp-testing",
    description: "Test local web applications using Playwright",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/webapp-testing",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "testing"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/webapp-testing/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-algorithmic-art",
    name: "algorithmic-art",
    description: "Create generative art using p5.js with seeded randomness",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/algorithmic-art",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "art"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/algorithmic-art/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-canvas-design",
    name: "canvas-design",
    description: "Design visual art in PNG and PDF formats",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/canvas-design",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "design"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/canvas-design/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-frontend-design",
    name: "frontend-design",
    description: "Frontend design and UI/UX development tools",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "frontend"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/frontend-design/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-theme-factory",
    name: "theme-factory",
    description: "Style artifacts with professional themes or generate custom themes",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/theme-factory",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "theme"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/theme-factory/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-web-artifacts-builder",
    name: "web-artifacts-builder",
    description: "Build complex HTML artifacts with React and Tailwind",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "web"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/web-artifacts-builder/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-slack-gif-creator",
    name: "slack-gif-creator",
    description: "Create animated GIFs optimized for Slack size constraints",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/slack-gif-creator",
    stars: 1500,
    category: "communication",
    tags: ["anthropics", "official", "slack"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/slack-gif-creator/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-internal-comms",
    name: "internal-comms",
    description: "Write status reports, newsletters, and FAQs",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/internal-comms",
    stars: 1500,
    category: "content",
    tags: ["anthropics", "official", "writing"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/internal-comms/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-brand-guidelines",
    name: "brand-guidelines",
    description: "Apply Anthropic's brand colors and typography to artifacts",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/brand-guidelines",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "brand"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/brand-guidelines/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Vercel Skills (8) ==========
  {
    id: "vercel-react-best-practices",
    name: "react-best-practices",
    description: "React best practices and patterns from Vercel",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "react", "best-practices"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-next-best-practices",
    name: "next-best-practices",
    description: "Next.js best practices and recommended patterns",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/next-skills/tree/main/skills/next-best-practices",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "nextjs", "best-practices"],
    skill_md_url: "https://github.com/vercel-labs/next-skills/blob/main/skills/next-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-web-design-guidelines",
    name: "web-design-guidelines",
    description: "Web design guidelines and standards from Vercel",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines",
    stars: 800,
    category: "design",
    tags: ["vercel", "design", "web"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/web-design-guidelines/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-composition-patterns",
    name: "composition-patterns",
    description: "React component composition and reusable patterns",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/composition-patterns",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "react", "patterns"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/composition-patterns/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-next-upgrade",
    name: "next-upgrade",
    description: "Upgrade Next.js projects to newer versions",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/next-skills/tree/main/skills/next-upgrade",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "nextjs", "upgrade"],
    skill_md_url: "https://github.com/vercel-labs/next-skills/blob/main/skills/next-upgrade/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-react-native-skills",
    name: "react-native-skills",
    description: "React Native best practices and performance guidelines",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-native-skills",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "react-native", "mobile"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-next-cache-components",
    name: "next-cache-components",
    description: "Caching strategies and cache-aware components in Next.js",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/next-skills/tree/main/skills/next-cache-components",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "nextjs", "caching"],
    skill_md_url: "https://github.com/vercel-labs/next-skills/blob/main/skills/next-cache-components/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-deploy-claimable",
    name: "vercel-deploy-claimable",
    description: "Deploy projects to Vercel with claimable URLs",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/claude.ai/vercel-deploy-claimable",
    stars: 800,
    category: "automation",
    tags: ["vercel", "deploy", "hosting"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/claude.ai/vercel-deploy-claimable/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Cloudflare Skills (7) ==========
  {
    id: "cloudflare-wrangler",
    name: "wrangler",
    description: "Deploy and manage Workers, KV, R2, D1, Vectorize, Queues, Workflows",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/wrangler",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "workers", "deploy"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/wrangler/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "cloudflare-durable-objects",
    name: "durable-objects",
    description: "Stateful coordination with RPC, SQLite, and WebSockets",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/durable-objects",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "durable-objects", "state"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/durable-objects/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "cloudflare-agents-sdk",
    name: "agents-sdk",
    description: "Build stateful AI agents with scheduling, RPC, and MCP servers",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/agents-sdk",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "agents", "ai"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/agents-sdk/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "cloudflare-web-perf",
    name: "web-perf",
    description: "Audit Core Web Vitals and render-blocking resources",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/web-perf",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "performance", "web"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/web-perf/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== More Cloudflare Skills ==========
  {
    id: "cloudflare-building-ai-agent",
    name: "building-ai-agent-on-cloudflare",
    description: "Build AI agents with state and WebSockets on Cloudflare",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/building-ai-agent-on-cloudflare",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "ai", "agents"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/building-ai-agent-on-cloudflare/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "cloudflare-building-mcp-server",
    name: "building-mcp-server-on-cloudflare",
    description: "Build remote MCP servers with tools and OAuth",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/building-mcp-server-on-cloudflare",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "mcp", "oauth"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/building-mcp-server-on-cloudflare/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Supabase Skills ==========
  {
    id: "supabase-postgres-best-practices",
    name: "postgres-best-practices",
    description: "PostgreSQL best practices for Supabase",
    author: "supabase",
    repo_url: "https://github.com/supabase/agent-skills/tree/main/skills/supabase-postgres-best-practices",
    stars: 500,
    category: "data",
    tags: ["supabase", "postgres", "database"],
    skill_md_url: "https://github.com/supabase/agent-skills/blob/main/skills/supabase-postgres-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Stripe Skills ==========
  {
    id: "stripe-best-practices",
    name: "stripe-best-practices",
    description: "Best practices for building Stripe integrations",
    author: "stripe",
    repo_url: "https://github.com/stripe/ai/tree/main/skills/stripe-best-practices",
    stars: 400,
    category: "dev-tools",
    tags: ["stripe", "payments", "integration"],
    skill_md_url: "https://github.com/stripe/ai/blob/main/skills/stripe-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "stripe-upgrade",
    name: "upgrade-stripe",
    description: "Upgrade Stripe SDK and API versions",
    author: "stripe",
    repo_url: "https://github.com/stripe/ai/tree/main/skills/upgrade-stripe",
    stars: 400,
    category: "dev-tools",
    tags: ["stripe", "upgrade", "sdk"],
    skill_md_url: "https://github.com/stripe/ai/blob/main/skills/upgrade-stripe/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== HuggingFace Skills (8) ==========
  {
    id: "huggingface-cli",
    name: "hugging-face-cli",
    description: "HF Hub CLI for models, datasets, repos, and compute jobs",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-cli",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "cli"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-cli/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-model-trainer",
    name: "hugging-face-model-trainer",
    description: "Train models with TRL: SFT, DPO, GRPO, GGUF conversion",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-model-trainer",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "training"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-model-trainer/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-datasets",
    name: "hugging-face-datasets",
    description: "Create and manage datasets with configs and SQL querying",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-datasets",
    stars: 350,
    category: "data",
    tags: ["huggingface", "ml", "datasets"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-datasets/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-evaluation",
    name: "hugging-face-evaluation",
    description: "Model evaluation with vLLM/lighteval and eval tables",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-evaluation",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "evaluation"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-evaluation/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-jobs",
    name: "hugging-face-jobs",
    description: "Run compute jobs and Python scripts on HF infrastructure",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-jobs",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "compute"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-jobs/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-paper-publisher",
    name: "hugging-face-paper-publisher",
    description: "Publish papers on HF Hub with model/dataset links",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-paper-publisher",
    stars: 350,
    category: "content",
    tags: ["huggingface", "ml", "papers"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-paper-publisher/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-tool-builder",
    name: "hugging-face-tool-builder",
    description: "Build reusable scripts for HF API operations",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-tool-builder",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "tools"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-tool-builder/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-trackio",
    name: "hugging-face-trackio",
    description: "Track ML experiments with real-time dashboards",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-trackio",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "tracking"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-trackio/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Google Labs Skills (6) ==========
  {
    id: "google-shadcn-ui",
    name: "shadcn-ui",
    description: "Build UI components with shadcn/ui",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/shadcn-ui",
    stars: 300,
    category: "design",
    tags: ["google", "ui", "shadcn"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/shadcn-ui/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "google-react-components",
    name: "react-components",
    description: "Stitch to React components conversion",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/react-components",
    stars: 300,
    category: "design",
    tags: ["google", "react", "components"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/react-components/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "google-remotion",
    name: "remotion",
    description: "Generate walkthrough videos from Stitch app designs",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/remotion",
    stars: 300,
    category: "content",
    tags: ["google", "video", "remotion"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/remotion/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "google-design-md",
    name: "design-md",
    description: "Create and manage DESIGN.md files",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/design-md",
    stars: 300,
    category: "design",
    tags: ["google", "design", "documentation"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/design-md/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "google-enhance-prompt",
    name: "enhance-prompt",
    description: "Improve prompts with design specs and UI/UX vocabulary",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/enhance-prompt",
    stars: 300,
    category: "design",
    tags: ["google", "prompts", "ui-ux"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/enhance-prompt/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "google-stitch-loop",
    name: "stitch-loop",
    description: "Iterative design-to-code feedback loop",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/stitch-loop",
    stars: 300,
    category: "design",
    tags: ["google", "design", "iteration"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/stitch-loop/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Expo Skills (3) ==========
  {
    id: "expo-app-design",
    name: "expo-app-design",
    description: "Design Expo mobile applications",
    author: "expo",
    repo_url: "https://github.com/expo/skills/tree/main/plugins/expo-app-design",
    stars: 250,
    category: "design",
    tags: ["expo", "mobile", "react-native"],
    skill_md_url: "https://github.com/expo/skills/blob/main/plugins/expo-app-design/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "expo-deployment",
    name: "expo-deployment",
    description: "Deploy Expo apps to app stores",
    author: "expo",
    repo_url: "https://github.com/expo/skills/tree/main/plugins/expo-deployment",
    stars: 250,
    category: "automation",
    tags: ["expo", "deploy", "mobile"],
    skill_md_url: "https://github.com/expo/skills/blob/main/plugins/expo-deployment/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "expo-upgrading",
    name: "upgrading-expo",
    description: "Upgrade Expo SDK versions",
    author: "expo",
    repo_url: "https://github.com/expo/skills/tree/main/plugins/upgrading-expo",
    stars: 250,
    category: "dev-tools",
    tags: ["expo", "upgrade", "sdk"],
    skill_md_url: "https://github.com/expo/skills/blob/main/plugins/upgrading-expo/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Trail of Bits Security Skills (20+) ==========
  {
    id: "tob-static-analysis",
    name: "static-analysis",
    description: "Static analysis toolkit with CodeQL, Semgrep, and SARIF",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/static-analysis",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "analysis", "audit"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/static-analysis/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-semgrep-rule-creator",
    name: "semgrep-rule-creator",
    description: "Create and refine Semgrep rules for vulnerability detection",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/semgrep-rule-creator",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "semgrep", "rules"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/semgrep-rule-creator/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-property-based-testing",
    name: "property-based-testing",
    description: "Property-based testing for multiple languages and smart contracts",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/property-based-testing",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "testing", "fuzzing"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/property-based-testing/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-building-secure-contracts",
    name: "building-secure-contracts",
    description: "Smart contract security toolkit with vulnerability scanners for 6 blockchains",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/building-secure-contracts",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "blockchain", "smart-contracts"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/building-secure-contracts/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-audit-context-building",
    name: "audit-context-building",
    description: "Deep architectural context via ultra-granular code analysis",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/audit-context-building",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "audit", "analysis"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/audit-context-building/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-differential-review",
    name: "differential-review",
    description: "Security-focused diff review with git history analysis",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/differential-review",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "code-review", "git"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/differential-review/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-variant-analysis",
    name: "variant-analysis",
    description: "Find similar vulnerabilities via pattern-based analysis",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/variant-analysis",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "vulnerability", "patterns"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/variant-analysis/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-fix-review",
    name: "fix-review",
    description: "Verify fix commits address audit findings without new bugs",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/fix-review",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "audit", "review"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/fix-review/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-insecure-defaults",
    name: "insecure-defaults",
    description: "Detect insecure default configurations like hardcoded secrets and weak crypto",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/insecure-defaults",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "configuration", "secrets"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/insecure-defaults/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-modern-python",
    name: "modern-python",
    description: "Modern Python tooling with uv, ruff, ty, and pytest best practices",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/modern-python",
    stars: 200,
    category: "dev-tools",
    tags: ["python", "tooling", "best-practices"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/modern-python/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-testing-handbook-skills",
    name: "testing-handbook-skills",
    description: "Testing Handbook skills: fuzzers, static analysis, sanitizers",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/testing-handbook-skills",
    stars: 200,
    category: "dev-tools",
    tags: ["testing", "security", "fuzzing"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/testing-handbook-skills/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Sentry Skills (7) ==========
  {
    id: "sentry-agents-md",
    name: "agents-md",
    description: "Generate and manage AGENTS.md files",
    author: "getsentry",
    repo_url: "https://github.com/getsentry/skills/tree/main/plugins/sentry-skills/skills/agents-md",
    stars: 180,
    category: "dev-tools",
    tags: ["sentry", "documentation", "agents"],
    skill_md_url: "https://github.com/getsentry/skills/blob/main/plugins/sentry-skills/skills/agents-md/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "sentry-code-review",
    name: "code-review",
    description: "Perform code reviews with best practices",
    author: "getsentry",
    repo_url: "https://github.com/getsentry/skills/tree/main/plugins/sentry-skills/skills/code-review",
    stars: 180,
    category: "dev-tools",
    tags: ["sentry", "code-review", "quality"],
    skill_md_url: "https://github.com/getsentry/skills/blob/main/plugins/sentry-skills/skills/code-review/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "sentry-commit",
    name: "commit",
    description: "Create commits with best practices",
    author: "getsentry",
    repo_url: "https://github.com/getsentry/skills/tree/main/plugins/sentry-skills/skills/commit",
    stars: 180,
    category: "dev-tools",
    tags: ["sentry", "git", "commit"],
    skill_md_url: "https://github.com/getsentry/skills/blob/main/plugins/sentry-skills/skills/commit/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "sentry-create-pr",
    name: "create-pr",
    description: "Create pull requests with proper format",
    author: "getsentry",
    repo_url: "https://github.com/getsentry/skills/tree/main/plugins/sentry-skills/skills/create-pr",
    stars: 180,
    category: "dev-tools",
    tags: ["sentry", "git", "pull-request"],
    skill_md_url: "https://github.com/getsentry/skills/blob/main/plugins/sentry-skills/skills/create-pr/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "sentry-find-bugs",
    name: "find-bugs",
    description: "Find and identify bugs in code",
    author: "getsentry",
    repo_url: "https://github.com/getsentry/skills/tree/main/plugins/sentry-skills/skills/find-bugs",
    stars: 180,
    category: "dev-tools",
    tags: ["sentry", "debugging", "bugs"],
    skill_md_url: "https://github.com/getsentry/skills/blob/main/plugins/sentry-skills/skills/find-bugs/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== CallStack React Native Skills (3) ==========
  {
    id: "callstack-react-native-best-practices",
    name: "react-native-best-practices",
    description: "Performance optimization for React Native apps from Callstack",
    author: "callstackincubator",
    repo_url: "https://github.com/callstackincubator/agent-skills/tree/main/skills/react-native-best-practices",
    stars: 150,
    category: "dev-tools",
    tags: ["react-native", "mobile", "performance"],
    skill_md_url: "https://github.com/callstackincubator/agent-skills/blob/main/skills/react-native-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "callstack-github",
    name: "github-workflow",
    description: "GitHub workflow patterns for PRs, code review, branching",
    author: "callstackincubator",
    repo_url: "https://github.com/callstackincubator/agent-skills/tree/main/skills/github",
    stars: 150,
    category: "dev-tools",
    tags: ["github", "workflow", "git"],
    skill_md_url: "https://github.com/callstackincubator/agent-skills/blob/main/skills/github/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "callstack-upgrading-react-native",
    name: "upgrading-react-native",
    description: "React Native upgrade workflow: templates, dependencies, and common pitfalls",
    author: "callstackincubator",
    repo_url: "https://github.com/callstackincubator/agent-skills/tree/main/skills/upgrading-react-native",
    stars: 150,
    category: "dev-tools",
    tags: ["react-native", "upgrade", "mobile"],
    skill_md_url: "https://github.com/callstackincubator/agent-skills/blob/main/skills/upgrading-react-native/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== HashiCorp Terraform Skills (3) ==========
  {
    id: "hashicorp-terraform-code-generation",
    name: "terraform-code-generation",
    description: "Generate and validate Terraform HCL code",
    author: "hashicorp",
    repo_url: "https://github.com/hashicorp/agent-skills/tree/main/terraform/code-generation",
    stars: 300,
    category: "automation",
    tags: ["terraform", "iac", "devops"],
    skill_md_url: "https://github.com/hashicorp/agent-skills/blob/main/terraform/code-generation/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "hashicorp-terraform-module-generation",
    name: "terraform-module-generation",
    description: "Create and refactor Terraform modules",
    author: "hashicorp",
    repo_url: "https://github.com/hashicorp/agent-skills/tree/main/terraform/module-generation",
    stars: 300,
    category: "automation",
    tags: ["terraform", "modules", "iac"],
    skill_md_url: "https://github.com/hashicorp/agent-skills/blob/main/terraform/module-generation/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "hashicorp-terraform-provider-development",
    name: "terraform-provider-development",
    description: "Develop Terraform providers",
    author: "hashicorp",
    repo_url: "https://github.com/hashicorp/agent-skills/tree/main/terraform/provider-development",
    stars: 300,
    category: "dev-tools",
    tags: ["terraform", "providers", "development"],
    skill_md_url: "https://github.com/hashicorp/agent-skills/blob/main/terraform/provider-development/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== OpenAI Official Skills (Selected) ==========
  {
    id: "openai-playwright",
    name: "playwright",
    description: "Automate real browser interactions for navigation, forms, and scraping",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/playwright",
    stars: 500,
    category: "dev-tools",
    tags: ["openai", "testing", "browser"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/playwright/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-security-best-practices",
    name: "security-best-practices",
    description: "Review code for language-specific security vulnerabilities",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/security-best-practices",
    stars: 500,
    category: "dev-tools",
    tags: ["openai", "security", "review"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/security-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-gh-fix-ci",
    name: "gh-fix-ci",
    description: "Debug and fix failing GitHub Actions PR checks using log inspection",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/gh-fix-ci",
    stars: 500,
    category: "dev-tools",
    tags: ["openai", "ci", "github-actions"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/gh-fix-ci/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-jupyter-notebook",
    name: "jupyter-notebook",
    description: "Create clean, reproducible Jupyter notebooks for experiments and tutorials",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/jupyter-notebook",
    stars: 500,
    category: "data",
    tags: ["openai", "jupyter", "notebooks"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/jupyter-notebook/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-linear",
    name: "linear",
    description: "Manage issues, projects, and team workflows in Linear",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/linear",
    stars: 500,
    category: "productivity",
    tags: ["openai", "linear", "project-management"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/linear/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-vercel-deploy",
    name: "vercel-deploy",
    description: "Deploy applications and websites to Vercel with preview or production options",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/vercel-deploy",
    stars: 500,
    category: "automation",
    tags: ["openai", "vercel", "deploy"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/vercel-deploy/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-cloudflare-deploy",
    name: "cloudflare-deploy",
    description: "Deploy apps to Cloudflare using Workers, Pages, and platform services",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/cloudflare-deploy",
    stars: 500,
    category: "automation",
    tags: ["openai", "cloudflare", "deploy"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/cloudflare-deploy/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-doc",
    name: "doc",
    description: "Read, create, and edit .docx documents with formatting and layout fidelity",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/doc",
    stars: 500,
    category: "productivity",
    tags: ["openai", "document", "docx"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/doc/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-pdf",
    name: "pdf",
    description: "Read, create, and review PDFs with layout and visual formatting integrity",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/pdf",
    stars: 500,
    category: "productivity",
    tags: ["openai", "pdf", "document"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/pdf/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "openai-spreadsheet",
    name: "spreadsheet",
    description: "Create, edit, analyze, and visualize spreadsheets with formulas",
    author: "openai",
    repo_url: "https://github.com/openai/skills/tree/main/skills/.curated/spreadsheet",
    stars: 500,
    category: "data",
    tags: ["openai", "spreadsheet", "excel"],
    skill_md_url: "https://github.com/openai/skills/blob/main/skills/.curated/spreadsheet/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Neon Serverless Postgres ==========
  {
    id: "neon-using-neon",
    name: "using-neon",
    description: "Best practices for Neon Serverless Postgres",
    author: "neondatabase",
    repo_url: "https://github.com/neondatabase/agent-skills/tree/main/skills/neon-postgres",
    stars: 180,
    category: "data",
    tags: ["neon", "postgres", "serverless"],
    skill_md_url: "https://github.com/neondatabase/agent-skills/blob/main/skills/neon-postgres/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Sanity CMS Skills (4) ==========
  {
    id: "sanity-best-practices",
    name: "sanity-best-practices",
    description: "Best practices for Sanity Studio, GROQ queries, and content workflows",
    author: "sanity-io",
    repo_url: "https://github.com/sanity-io/agent-toolkit/tree/main/skills/sanity-best-practices",
    stars: 150,
    category: "dev-tools",
    tags: ["sanity", "cms", "content"],
    skill_md_url: "https://github.com/sanity-io/agent-toolkit/blob/main/skills/sanity-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "sanity-content-modeling",
    name: "content-modeling-best-practices",
    description: "Guidelines for designing scalable content models in Sanity",
    author: "sanity-io",
    repo_url: "https://github.com/sanity-io/agent-toolkit/tree/main/skills/content-modeling-best-practices",
    stars: 150,
    category: "dev-tools",
    tags: ["sanity", "content-modeling", "cms"],
    skill_md_url: "https://github.com/sanity-io/agent-toolkit/blob/main/skills/content-modeling-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== fal.ai AI Skills (6) ==========
  {
    id: "fal-generate",
    name: "fal-generate",
    description: "Generate images and videos using fal.ai AI models",
    author: "fal-ai-community",
    repo_url: "https://github.com/fal-ai-community/skills/tree/main/skills/claude.ai/fal-generate",
    stars: 120,
    category: "design",
    tags: ["fal", "ai", "image-generation"],
    skill_md_url: "https://github.com/fal-ai-community/skills/blob/main/skills/claude.ai/fal-generate/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "fal-audio",
    name: "fal-audio",
    description: "Text-to-speech and speech-to-text using fal.ai audio models",
    author: "fal-ai-community",
    repo_url: "https://github.com/fal-ai-community/skills/tree/main/skills/claude.ai/fal-audio",
    stars: 120,
    category: "content",
    tags: ["fal", "ai", "audio"],
    skill_md_url: "https://github.com/fal-ai-community/skills/blob/main/skills/claude.ai/fal-audio/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "fal-image-edit",
    name: "fal-image-edit",
    description: "AI-powered image editing with style transfer and object removal",
    author: "fal-ai-community",
    repo_url: "https://github.com/fal-ai-community/skills/tree/main/skills/claude.ai/fal-image-edit",
    stars: 120,
    category: "design",
    tags: ["fal", "ai", "image-editing"],
    skill_md_url: "https://github.com/fal-ai-community/skills/blob/main/skills/claude.ai/fal-image-edit/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "fal-upscale",
    name: "fal-upscale",
    description: "Upscale and enhance image and video resolution using AI",
    author: "fal-ai-community",
    repo_url: "https://github.com/fal-ai-community/skills/tree/main/skills/claude.ai/fal-upscale",
    stars: 120,
    category: "design",
    tags: ["fal", "ai", "upscale"],
    skill_md_url: "https://github.com/fal-ai-community/skills/blob/main/skills/claude.ai/fal-upscale/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Remotion Video ==========
  {
    id: "remotion-video",
    name: "remotion",
    description: "Programmatic video creation with React",
    author: "remotion-dev",
    repo_url: "https://github.com/remotion-dev/skills/tree/main/skills/remotion",
    stars: 200,
    category: "content",
    tags: ["remotion", "video", "react"],
    skill_md_url: "https://github.com/remotion-dev/skills/blob/main/skills/remotion/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Replicate AI Models ==========
  {
    id: "replicate-ai",
    name: "replicate",
    description: "Discover, compare, and run AI models using Replicate's API",
    author: "replicate",
    repo_url: "https://github.com/replicate/skills/tree/main/skills/replicate",
    stars: 180,
    category: "dev-tools",
    tags: ["replicate", "ai", "models"],
    skill_md_url: "https://github.com/replicate/skills/blob/main/skills/replicate/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Tinybird Analytics ==========
  {
    id: "tinybird-best-practices",
    name: "tinybird-best-practices",
    description: "Tinybird project guidelines for datasources, pipes, endpoints, and SQL",
    author: "tinybirdco",
    repo_url: "https://github.com/tinybirdco/tinybird-agent-skills/tree/main/skills/tinybird-best-practices",
    stars: 140,
    category: "data",
    tags: ["tinybird", "analytics", "sql"],
    skill_md_url: "https://github.com/tinybirdco/tinybird-agent-skills/blob/main/skills/tinybird-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Firecrawl Web Scraping ==========
  {
    id: "firecrawl-cli",
    name: "firecrawl-cli",
    description: "Scrape, crawl, search, and map the web via CLI",
    author: "firecrawl",
    repo_url: "https://github.com/firecrawl/cli/tree/main/skills/firecrawl-cli",
    stars: 160,
    category: "dev-tools",
    tags: ["firecrawl", "web-scraping", "cli"],
    skill_md_url: "https://github.com/firecrawl/cli/blob/main/skills/firecrawl-cli/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Community High-Quality Skills ==========
  {
    id: "alirezarezvani-brainstorm",
    name: "brainstorm",
    description: "Structured brainstorming and idea generation",
    author: "alirezarezvani",
    repo_url: "https://github.com/alirezarezvani/claude-skills",
    stars: 1892,
    category: "productivity",
    tags: ["brainstorm", "planning", "ideas"],
    skill_md_url: "https://github.com/alirezarezvani/claude-skills/blob/main/skills/brainstorm/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "timescale-pg-aiguide",
    name: "pg-aiguide",
    description: "PostgreSQL AI guide for database optimization",
    author: "timescale",
    repo_url: "https://github.com/timescale/pg-aiguide",
    stars: 1553,
    category: "data",
    tags: ["postgres", "ai", "database"],
    skill_md_url: "https://github.com/timescale/pg-aiguide/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "antonbabenko-terraform",
    name: "terraform-skill",
    description: "Terraform infrastructure as code best practices",
    author: "antonbabenko",
    repo_url: "https://github.com/antonbabenko/terraform-skill",
    stars: 1124,
    category: "automation",
    tags: ["terraform", "iac", "devops"],
    skill_md_url: "https://github.com/antonbabenko/terraform-skill/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "addyosmani-web-quality",
    name: "web-quality-skills",
    description: "Web quality and performance best practices by Addy Osmani",
    author: "addyosmani",
    repo_url: "https://github.com/addyosmani/web-quality-skills",
    stars: 564,
    category: "dev-tools",
    tags: ["web", "performance", "quality"],
    skill_md_url: "https://github.com/addyosmani/web-quality-skills/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== obra/superpowers Skills (Battle-tested) ==========
  {
    id: "obra-test-driven-development",
    name: "test-driven-development",
    description: "Enforces RED-GREEN-REFACTOR cycle with testing anti-patterns reference",
    author: "obra",
    repo_url: "https://github.com/obra/superpowers/tree/main/skills/test-driven-development",
    stars: 500,
    category: "dev-tools",
    tags: ["tdd", "testing", "best-practices"],
    skill_md_url: "https://github.com/obra/superpowers/blob/main/skills/test-driven-development/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "obra-systematic-debugging",
    name: "systematic-debugging",
    description: "Four-phase root cause analysis process",
    author: "obra",
    repo_url: "https://github.com/obra/superpowers/tree/main/skills/systematic-debugging",
    stars: 500,
    category: "dev-tools",
    tags: ["debugging", "analysis", "troubleshooting"],
    skill_md_url: "https://github.com/obra/superpowers/blob/main/skills/systematic-debugging/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "obra-writing-plans",
    name: "writing-plans",
    description: "Creates detailed implementation plans with bite-sized tasks",
    author: "obra",
    repo_url: "https://github.com/obra/superpowers/tree/main/skills/writing-plans",
    stars: 500,
    category: "productivity",
    tags: ["planning", "tasks", "implementation"],
    skill_md_url: "https://github.com/obra/superpowers/blob/main/skills/writing-plans/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "obra-dispatching-parallel-agents",
    name: "dispatching-parallel-agents",
    description: "Manages concurrent subagent workflows",
    author: "obra",
    repo_url: "https://github.com/obra/superpowers/tree/main/skills/dispatching-parallel-agents",
    stars: 500,
    category: "automation",
    tags: ["agents", "parallel", "orchestration"],
    skill_md_url: "https://github.com/obra/superpowers/blob/main/skills/dispatching-parallel-agents/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "obra-code-review",
    name: "requesting-code-review",
    description: "Pre-review checklist and code inspection workflow",
    author: "obra",
    repo_url: "https://github.com/obra/superpowers/tree/main/skills/requesting-code-review",
    stars: 500,
    category: "dev-tools",
    tags: ["code-review", "quality", "git"],
    skill_md_url: "https://github.com/obra/superpowers/blob/main/skills/requesting-code-review/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "obra-git-worktrees",
    name: "using-git-worktrees",
    description: "Parallel development with isolated Git workspaces",
    author: "obra",
    repo_url: "https://github.com/obra/superpowers/tree/main/skills/using-git-worktrees",
    stars: 500,
    category: "dev-tools",
    tags: ["git", "worktrees", "workflow"],
    skill_md_url: "https://github.com/obra/superpowers/blob/main/skills/using-git-worktrees/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "obra-defense-in-depth",
    name: "defense-in-depth",
    description: "Multi-layered security approaches",
    author: "obra",
    repo_url: "https://github.com/obra/superpowers/tree/main/skills/defense-in-depth",
    stars: 500,
    category: "dev-tools",
    tags: ["security", "defense", "best-practices"],
    skill_md_url: "https://github.com/obra/superpowers/blob/main/skills/defense-in-depth/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== wondelai/skills - Business Framework Skills (131 stars) ==========
  {
    id: "wondelai-jobs-to-be-done",
    name: "jobs-to-be-done",
    description: "Clayton Christensen's framework: customers hire products to make progress",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/jobs-to-be-done",
    stars: 131,
    category: "productivity",
    tags: ["business", "product", "strategy"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/jobs-to-be-done/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-lean-startup",
    name: "lean-startup",
    description: "Build-Measure-Learn methodology for validating ideas",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/lean-startup",
    stars: 131,
    category: "productivity",
    tags: ["startup", "lean", "validation"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/lean-startup/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-design-sprint",
    name: "design-sprint",
    description: "5-day prototyping and testing process by Jake Knapp",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/design-sprint",
    stars: 131,
    category: "design",
    tags: ["design", "sprint", "prototype"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/design-sprint/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-refactoring-ui",
    name: "refactoring-ui",
    description: "Practical UI system for developers by Adam Wathan & Steve Schoger",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/refactoring-ui",
    stars: 131,
    category: "design",
    tags: ["ui", "design", "tailwind"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/refactoring-ui/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-ios-hig-design",
    name: "ios-hig-design",
    description: "Native iOS app design following Apple Human Interface Guidelines",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/ios-hig-design",
    stars: 131,
    category: "design",
    tags: ["ios", "apple", "hig"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/ios-hig-design/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-hooked-ux",
    name: "hooked-ux",
    description: "Habit-forming product design by Nir Eyal",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/hooked-ux",
    stars: 131,
    category: "design",
    tags: ["ux", "product", "engagement"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/hooked-ux/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-storybrand",
    name: "storybrand-messaging",
    description: "Story structure for clear brand communication",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/storybrand-messaging",
    stars: 131,
    category: "content",
    tags: ["marketing", "storytelling", "brand"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/storybrand-messaging/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-hundred-million-offers",
    name: "hundred-million-offers",
    description: "Grand Slam offer creation by Alex Hormozi",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/hundred-million-offers",
    stars: 131,
    category: "content",
    tags: ["marketing", "offers", "sales"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/hundred-million-offers/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-negotiation",
    name: "negotiation",
    description: "FBI-based tactical negotiation by Chris Voss",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/negotiation",
    stars: 131,
    category: "productivity",
    tags: ["negotiation", "sales", "communication"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/negotiation/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wondelai-blue-ocean-strategy",
    name: "blue-ocean-strategy",
    description: "Create uncontested market space",
    author: "wondelai",
    repo_url: "https://github.com/wondelai/skills/tree/main/skills/blue-ocean-strategy",
    stars: 131,
    category: "productivity",
    tags: ["strategy", "business", "market"],
    skill_md_url: "https://github.com/wondelai/skills/blob/main/skills/blue-ocean-strategy/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== zxkane/aws-skills - AWS Development (200+ stars) ==========
  {
    id: "zxkane-aws-cdk",
    name: "aws-cdk",
    description: "AWS CDK best practices, patterns, and pre-deployment validation",
    author: "zxkane",
    repo_url: "https://github.com/zxkane/aws-skills/tree/main/skills/aws-cdk",
    stars: 200,
    category: "automation",
    tags: ["aws", "cdk", "infrastructure"],
    skill_md_url: "https://github.com/zxkane/aws-skills/blob/main/skills/aws-cdk/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "zxkane-aws-serverless",
    name: "aws-serverless",
    description: "Serverless design, event-driven patterns, Step Functions orchestration",
    author: "zxkane",
    repo_url: "https://github.com/zxkane/aws-skills/tree/main/skills/aws-serverless",
    stars: 200,
    category: "automation",
    tags: ["aws", "serverless", "lambda"],
    skill_md_url: "https://github.com/zxkane/aws-skills/blob/main/skills/aws-serverless/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "zxkane-aws-cost-ops",
    name: "aws-cost-operations",
    description: "AWS cost estimation, monitoring patterns, and operational excellence",
    author: "zxkane",
    repo_url: "https://github.com/zxkane/aws-skills/tree/main/skills/aws-cost-ops",
    stars: 200,
    category: "automation",
    tags: ["aws", "cost", "operations"],
    skill_md_url: "https://github.com/zxkane/aws-skills/blob/main/skills/aws-cost-ops/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== levnikolaevich/claude-code-skills - Full Dev Workflow (105 stars) ==========
  {
    id: "levnikolaevich-documents-pipeline",
    name: "documents-pipeline",
    description: "Orchestrator for complete documentation generation",
    author: "levnikolaevich",
    repo_url: "https://github.com/levnikolaevich/claude-code-skills/tree/main/skills/ln-100-documents-pipeline",
    stars: 105,
    category: "content",
    tags: ["documentation", "pipeline", "automation"],
    skill_md_url: "https://github.com/levnikolaevich/claude-code-skills/blob/main/skills/ln-100-documents-pipeline/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "levnikolaevich-scope-decomposer",
    name: "scope-decomposer",
    description: "Converts scope into Epics and Stories",
    author: "levnikolaevich",
    repo_url: "https://github.com/levnikolaevich/claude-code-skills/tree/main/skills/ln-200-scope-decomposer",
    stars: 105,
    category: "productivity",
    tags: ["planning", "agile", "decomposition"],
    skill_md_url: "https://github.com/levnikolaevich/claude-code-skills/blob/main/skills/ln-200-scope-decomposer/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "levnikolaevich-story-executor",
    name: "story-executor",
    description: "Fully automated story-to-Done pipeline",
    author: "levnikolaevich",
    repo_url: "https://github.com/levnikolaevich/claude-code-skills/tree/main/skills/ln-400-story-executor",
    stars: 105,
    category: "automation",
    tags: ["agile", "automation", "stories"],
    skill_md_url: "https://github.com/levnikolaevich/claude-code-skills/blob/main/skills/ln-400-story-executor/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "levnikolaevich-code-quality-checker",
    name: "code-quality-checker",
    description: "Detects DRY/KISS/YAGNI violations and code smells",
    author: "levnikolaevich",
    repo_url: "https://github.com/levnikolaevich/claude-code-skills/tree/main/skills/ln-511-code-quality-checker",
    stars: 105,
    category: "dev-tools",
    tags: ["quality", "linting", "best-practices"],
    skill_md_url: "https://github.com/levnikolaevich/claude-code-skills/blob/main/skills/ln-511-code-quality-checker/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "levnikolaevich-security-auditor",
    name: "security-auditor",
    description: "Detects secrets, SQL injection, XSS vulnerabilities",
    author: "levnikolaevich",
    repo_url: "https://github.com/levnikolaevich/claude-code-skills/tree/main/skills/ln-621-security-auditor",
    stars: 105,
    category: "dev-tools",
    tags: ["security", "audit", "vulnerabilities"],
    skill_md_url: "https://github.com/levnikolaevich/claude-code-skills/blob/main/skills/ln-621-security-auditor/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "levnikolaevich-project-bootstrap",
    name: "project-bootstrap",
    description: "Creates new or transforms existing projects to Clean Architecture",
    author: "levnikolaevich",
    repo_url: "https://github.com/levnikolaevich/claude-code-skills/tree/main/skills/ln-700-project-bootstrap",
    stars: 105,
    category: "dev-tools",
    tags: ["bootstrap", "architecture", "scaffold"],
    skill_md_url: "https://github.com/levnikolaevich/claude-code-skills/blob/main/skills/ln-700-project-bootstrap/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== ComposioHQ Skills (Popular) ==========
  {
    id: "composio-changelog-generator",
    name: "changelog-generator",
    description: "Transforms git commits into user-facing release notes",
    author: "ComposioHQ",
    repo_url: "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/changelog-generator",
    stars: 150,
    category: "dev-tools",
    tags: ["git", "changelog", "releases"],
    skill_md_url: "https://github.com/ComposioHQ/awesome-claude-skills/blob/master/changelog-generator/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "composio-content-research-writer",
    name: "content-research-writer",
    description: "Research-backed content creation with citations",
    author: "ComposioHQ",
    repo_url: "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/content-research-writer",
    stars: 150,
    category: "content",
    tags: ["research", "writing", "content"],
    skill_md_url: "https://github.com/ComposioHQ/awesome-claude-skills/blob/master/content-research-writer/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "composio-csv-summarizer",
    name: "csv-data-summarizer",
    description: "Automatic CSV analysis with visualizations",
    author: "ComposioHQ",
    repo_url: "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/csv-data-summarizer",
    stars: 150,
    category: "data",
    tags: ["csv", "analysis", "visualization"],
    skill_md_url: "https://github.com/ComposioHQ/awesome-claude-skills/blob/master/csv-data-summarizer/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "composio-d3-visualization",
    name: "d3-visualization",
    description: "Data visualization and interactive charts with D3.js",
    author: "ComposioHQ",
    repo_url: "https://github.com/ComposioHQ/awesome-claude-skills/tree/master/d3-visualization",
    stars: 150,
    category: "data",
    tags: ["d3", "visualization", "charts"],
    skill_md_url: "https://github.com/ComposioHQ/awesome-claude-skills/blob/master/d3-visualization/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== More Popular Community Skills ==========
  {
    id: "keskinonur-ios-dev-guide",
    name: "ios-dev-guide",
    description: "iOS development guide for Claude Code",
    author: "keskinonur",
    repo_url: "https://github.com/keskinonur/claude-code-ios-dev-guide",
    stars: 356,
    category: "dev-tools",
    tags: ["ios", "swift", "mobile"],
    skill_md_url: "https://github.com/keskinonur/claude-code-ios-dev-guide/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "jabrena-cursor-rules-java",
    name: "cursor-rules-java",
    description: "Java development rules and best practices",
    author: "jabrena",
    repo_url: "https://github.com/jabrena/cursor-rules-java",
    stars: 294,
    category: "dev-tools",
    tags: ["java", "best-practices", "rules"],
    skill_md_url: "https://github.com/jabrena/cursor-rules-java/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "jiweiyeah-skills-manager",
    name: "skills-manager",
    description: "Manage and organize Claude Code skills",
    author: "jiweiyeah",
    repo_url: "https://github.com/jiweiyeah/Skills-Manager",
    stars: 261,
    category: "productivity",
    tags: ["skills", "management", "organization"],
    skill_md_url: "https://github.com/jiweiyeah/Skills-Manager/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== K-Dense-AI Scientific Skills (9000+ stars) ==========
  {
    id: "kdense-bioinformatics",
    name: "bioinformatics",
    description: "Sequence analysis, single-cell analysis with Scanpy, BioPython",
    author: "K-Dense-AI",
    repo_url: "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/skills/bioinformatics",
    stars: 9000,
    category: "data",
    tags: ["science", "bioinformatics", "genomics"],
    skill_md_url: "https://github.com/K-Dense-AI/claude-scientific-skills/blob/main/skills/bioinformatics/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "kdense-cheminformatics",
    name: "cheminformatics",
    description: "Molecular manipulation with RDKit, drug discovery, DeepChem",
    author: "K-Dense-AI",
    repo_url: "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/skills/cheminformatics",
    stars: 9000,
    category: "data",
    tags: ["science", "chemistry", "drug-discovery"],
    skill_md_url: "https://github.com/K-Dense-AI/claude-scientific-skills/blob/main/skills/cheminformatics/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "kdense-clinical-research",
    name: "clinical-research",
    description: "Variant interpretation, pharmacogenomics, clinical decision support",
    author: "K-Dense-AI",
    repo_url: "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/skills/clinical-research",
    stars: 9000,
    category: "data",
    tags: ["science", "clinical", "medicine"],
    skill_md_url: "https://github.com/K-Dense-AI/claude-scientific-skills/blob/main/skills/clinical-research/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "kdense-data-visualization",
    name: "scientific-visualization",
    description: "Publication-quality figures, network visualization, statistical analysis",
    author: "K-Dense-AI",
    repo_url: "https://github.com/K-Dense-AI/claude-scientific-skills/tree/main/skills/visualization",
    stars: 9000,
    category: "data",
    tags: ["science", "visualization", "statistics"],
    skill_md_url: "https://github.com/K-Dense-AI/claude-scientific-skills/blob/main/skills/visualization/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Orchestra-Research AI Research Skills (3700+ stars) ==========
  {
    id: "orchestra-model-architecture",
    name: "model-architecture",
    description: "LitGPT, Mamba, RWKV, NanoGPT, TorchTitan model architectures",
    author: "Orchestra-Research",
    repo_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/tree/main/skills/model-architecture",
    stars: 3700,
    category: "dev-tools",
    tags: ["ai", "ml", "architecture"],
    skill_md_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/blob/main/skills/model-architecture/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "orchestra-fine-tuning",
    name: "fine-tuning",
    description: "Axolotl, LLaMA-Factory, PEFT, Unsloth fine-tuning methods",
    author: "Orchestra-Research",
    repo_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/tree/main/skills/fine-tuning",
    stars: 3700,
    category: "dev-tools",
    tags: ["ai", "ml", "fine-tuning"],
    skill_md_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/blob/main/skills/fine-tuning/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "orchestra-mechanistic-interpretability",
    name: "mechanistic-interpretability",
    description: "TransformerLens, SAELens, pyvene for model interpretability",
    author: "Orchestra-Research",
    repo_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/tree/main/skills/interpretability",
    stars: 3700,
    category: "dev-tools",
    tags: ["ai", "ml", "interpretability"],
    skill_md_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/blob/main/skills/interpretability/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "orchestra-distributed-training",
    name: "distributed-training",
    description: "Megatron-Core, DeepSpeed, PyTorch FSDP2, Accelerate",
    author: "Orchestra-Research",
    repo_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/tree/main/skills/distributed-training",
    stars: 3700,
    category: "dev-tools",
    tags: ["ai", "ml", "distributed"],
    skill_md_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/blob/main/skills/distributed-training/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "orchestra-inference-serving",
    name: "inference-serving",
    description: "vLLM, TensorRT-LLM, llama.cpp, SGLang inference optimization",
    author: "Orchestra-Research",
    repo_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/tree/main/skills/inference",
    stars: 3700,
    category: "dev-tools",
    tags: ["ai", "ml", "inference"],
    skill_md_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/blob/main/skills/inference/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "orchestra-safety-alignment",
    name: "safety-alignment",
    description: "Constitutional AI, LlamaGuard, NeMo Guardrails, Prompt Guard",
    author: "Orchestra-Research",
    repo_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/tree/main/skills/safety",
    stars: 3700,
    category: "dev-tools",
    tags: ["ai", "safety", "alignment"],
    skill_md_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/blob/main/skills/safety/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "orchestra-rag",
    name: "rag-skills",
    description: "Chroma, FAISS, Sentence Transformers, Pinecone, Qdrant for RAG",
    author: "Orchestra-Research",
    repo_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/tree/main/skills/rag",
    stars: 3700,
    category: "dev-tools",
    tags: ["ai", "rag", "vector-db"],
    skill_md_url: "https://github.com/Orchestra-Research/AI-research-SKILLs/blob/main/skills/rag/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== OWASP Security Skill ==========
  {
    id: "agamm-owasp-security",
    name: "owasp-security",
    description: "OWASP Top 10:2025, ASVS 5.0, Agentic AI Security for 20+ languages",
    author: "agamm",
    repo_url: "https://github.com/agamm/claude-code-owasp",
    stars: 300,
    category: "dev-tools",
    tags: ["security", "owasp", "best-practices"],
    skill_md_url: "https://github.com/agamm/claude-code-owasp/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Apple HIG Skills (14 skills) ==========
  {
    id: "raintree-hig-foundations",
    name: "hig-foundations",
    description: "Color, typography, SF Symbols, dark mode, accessibility, layout",
    author: "raintree-technology",
    repo_url: "https://github.com/raintree-technology/apple-hig-skills/tree/main/skills/hig-foundations",
    stars: 180,
    category: "design",
    tags: ["apple", "ios", "design"],
    skill_md_url: "https://github.com/raintree-technology/apple-hig-skills/blob/main/skills/hig-foundations/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "raintree-hig-platforms",
    name: "hig-platforms",
    description: "Platform-specific design for iOS, iPadOS, macOS, tvOS, watchOS, visionOS",
    author: "raintree-technology",
    repo_url: "https://github.com/raintree-technology/apple-hig-skills/tree/main/skills/hig-platforms",
    stars: 180,
    category: "design",
    tags: ["apple", "ios", "platforms"],
    skill_md_url: "https://github.com/raintree-technology/apple-hig-skills/blob/main/skills/hig-platforms/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "raintree-hig-patterns",
    name: "hig-patterns",
    description: "UX patterns: onboarding, navigation, search, feedback, modality",
    author: "raintree-technology",
    repo_url: "https://github.com/raintree-technology/apple-hig-skills/tree/main/skills/hig-patterns",
    stars: 180,
    category: "design",
    tags: ["apple", "ux", "patterns"],
    skill_md_url: "https://github.com/raintree-technology/apple-hig-skills/blob/main/skills/hig-patterns/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "raintree-hig-components",
    name: "hig-components",
    description: "UI components: controls, dialogs, menus, status indicators",
    author: "raintree-technology",
    repo_url: "https://github.com/raintree-technology/apple-hig-skills/tree/main/skills/hig-components",
    stars: 180,
    category: "design",
    tags: ["apple", "ui", "components"],
    skill_md_url: "https://github.com/raintree-technology/apple-hig-skills/blob/main/skills/hig-components/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Marketing Skills (33 skills) ==========
  {
    id: "corey-copywriting",
    name: "copywriting",
    description: "Marketing page copy creation and optimization",
    author: "coreyhaines31",
    repo_url: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/copywriting",
    stars: 250,
    category: "content",
    tags: ["marketing", "copywriting", "conversion"],
    skill_md_url: "https://github.com/coreyhaines31/marketingskills/blob/main/skills/copywriting/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "corey-page-cro",
    name: "page-cro",
    description: "Optimize any marketing page for conversions",
    author: "coreyhaines31",
    repo_url: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/page-cro",
    stars: 250,
    category: "content",
    tags: ["marketing", "cro", "conversion"],
    skill_md_url: "https://github.com/coreyhaines31/marketingskills/blob/main/skills/page-cro/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "corey-seo-audit",
    name: "seo-audit",
    description: "Technical and on-page SEO optimization",
    author: "coreyhaines31",
    repo_url: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/seo-audit",
    stars: 250,
    category: "content",
    tags: ["marketing", "seo", "audit"],
    skill_md_url: "https://github.com/coreyhaines31/marketingskills/blob/main/skills/seo-audit/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "corey-cold-email",
    name: "cold-email",
    description: "B2B outreach sequences and templates",
    author: "coreyhaines31",
    repo_url: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/cold-email",
    stars: 250,
    category: "content",
    tags: ["marketing", "email", "outreach"],
    skill_md_url: "https://github.com/coreyhaines31/marketingskills/blob/main/skills/cold-email/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "corey-pricing-strategy",
    name: "pricing-strategy",
    description: "Monetization and pricing page optimization",
    author: "coreyhaines31",
    repo_url: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/pricing-strategy",
    stars: 250,
    category: "content",
    tags: ["marketing", "pricing", "strategy"],
    skill_md_url: "https://github.com/coreyhaines31/marketingskills/blob/main/skills/pricing-strategy/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "corey-marketing-psychology",
    name: "marketing-psychology",
    description: "Behavioral science principles for marketing",
    author: "coreyhaines31",
    repo_url: "https://github.com/coreyhaines31/marketingskills/tree/main/skills/marketing-psychology",
    stars: 250,
    category: "content",
    tags: ["marketing", "psychology", "behavior"],
    skill_md_url: "https://github.com/coreyhaines31/marketingskills/blob/main/skills/marketing-psychology/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== WordPress Skills (13 skills) ==========
  {
    id: "wordpress-block-development",
    name: "wp-block-development",
    description: "Gutenberg blocks: block.json, attributes, rendering, deprecations",
    author: "WordPress",
    repo_url: "https://github.com/WordPress/agent-skills/tree/trunk/skills/wp-block-development",
    stars: 300,
    category: "dev-tools",
    tags: ["wordpress", "gutenberg", "blocks"],
    skill_md_url: "https://github.com/WordPress/agent-skills/blob/trunk/skills/wp-block-development/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wordpress-plugin-development",
    name: "wp-plugin-development",
    description: "Plugin architecture, hooks, settings API, security",
    author: "WordPress",
    repo_url: "https://github.com/WordPress/agent-skills/tree/trunk/skills/wp-plugin-development",
    stars: 300,
    category: "dev-tools",
    tags: ["wordpress", "plugin", "php"],
    skill_md_url: "https://github.com/WordPress/agent-skills/blob/trunk/skills/wp-plugin-development/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wordpress-rest-api",
    name: "wp-rest-api",
    description: "REST API routes/endpoints, schema, auth, and response shaping",
    author: "WordPress",
    repo_url: "https://github.com/WordPress/agent-skills/tree/trunk/skills/wp-rest-api",
    stars: 300,
    category: "dev-tools",
    tags: ["wordpress", "rest-api", "backend"],
    skill_md_url: "https://github.com/WordPress/agent-skills/blob/trunk/skills/wp-rest-api/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "wordpress-performance",
    name: "wp-performance",
    description: "Profiling, caching, database optimization, Server-Timing",
    author: "WordPress",
    repo_url: "https://github.com/WordPress/agent-skills/tree/trunk/skills/wp-performance",
    stars: 300,
    category: "dev-tools",
    tags: ["wordpress", "performance", "optimization"],
    skill_md_url: "https://github.com/WordPress/agent-skills/blob/trunk/skills/wp-performance/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Transloadit Media Skills (6 skills) ==========
  {
    id: "transloadit-media",
    name: "transloadit",
    description: "Routes media tasks to 86+ processing Robots for images/videos",
    author: "transloadit",
    repo_url: "https://github.com/transloadit/skills/tree/main/skills/transloadit",
    stars: 150,
    category: "content",
    tags: ["media", "video", "image"],
    skill_md_url: "https://github.com/transloadit/skills/blob/main/skills/transloadit/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "transloadit-hls-video",
    name: "encode-hls-video",
    description: "Encode video to HLS streaming format",
    author: "transloadit",
    repo_url: "https://github.com/transloadit/skills/tree/main/skills/transform-encode-hls-video-with-transloadit",
    stars: 150,
    category: "content",
    tags: ["video", "hls", "streaming"],
    skill_md_url: "https://github.com/transloadit/skills/blob/main/skills/transform-encode-hls-video-with-transloadit/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Better Auth Skills (3 skills) ==========
  {
    id: "betterauth-best-practices",
    name: "better-auth-best-practices",
    description: "Best practices for Better Auth integration",
    author: "better-auth",
    repo_url: "https://github.com/better-auth/skills/tree/main/better-auth/best-practices",
    stars: 120,
    category: "dev-tools",
    tags: ["auth", "security", "best-practices"],
    skill_md_url: "https://github.com/better-auth/skills/blob/main/better-auth/best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "betterauth-create-auth",
    name: "create-auth",
    description: "Create authentication setup with Better Auth",
    author: "better-auth",
    repo_url: "https://github.com/better-auth/skills/tree/main/better-auth/create-auth",
    stars: 120,
    category: "dev-tools",
    tags: ["auth", "setup", "authentication"],
    skill_md_url: "https://github.com/better-auth/skills/blob/main/better-auth/create-auth/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
];
