import type { Skill } from "@/types/skill";

// 默认 skills 数据 - 官方和高质量 skills
// 只包含真正有 SKILL.md 的可安装 skills
export const DEFAULT_SKILLS: Skill[] = [
  // ========== Anthropic Official Skills (16) ==========
  {
    id: "anthropics-docx",
    name: "docx",
    description: "Create, edit, and analyze Word documents",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/docx",
    stars: 1500,
    category: "productivity",
    tags: ["anthropics", "official", "document"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/docx/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-pdf",
    name: "pdf",
    description: "Extract text, create PDFs, and handle forms",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/pdf",
    stars: 1500,
    category: "productivity",
    tags: ["anthropics", "official", "pdf"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/pdf/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-xlsx",
    name: "xlsx",
    description: "Create, edit, and analyze Excel spreadsheets",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/xlsx",
    stars: 1500,
    category: "data",
    tags: ["anthropics", "official", "excel"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/xlsx/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-pptx",
    name: "pptx",
    description: "Create, edit, and analyze PowerPoint presentations",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/pptx",
    stars: 1500,
    category: "productivity",
    tags: ["anthropics", "official", "powerpoint"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/pptx/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-doc-coauthoring",
    name: "doc-coauthoring",
    description: "Collaborative document editing and co-authoring",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/doc-coauthoring",
    stars: 1500,
    category: "content",
    tags: ["anthropics", "official", "collaboration"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/doc-coauthoring/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-mcp-builder",
    name: "mcp-builder",
    description: "Create MCP servers to integrate external APIs and services",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/mcp-builder",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "mcp"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/mcp-builder/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-skill-creator",
    name: "skill-creator",
    description: "Guide for creating skills that extend Claude's capabilities",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/skill-creator",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "meta"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/skill-creator/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-webapp-testing",
    name: "webapp-testing",
    description: "Test local web applications using Playwright",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/webapp-testing",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "testing"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/webapp-testing/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-algorithmic-art",
    name: "algorithmic-art",
    description: "Create generative art using p5.js with seeded randomness",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/algorithmic-art",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "art"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/algorithmic-art/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-canvas-design",
    name: "canvas-design",
    description: "Design visual art in PNG and PDF formats",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/canvas-design",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "design"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/canvas-design/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-frontend-design",
    name: "frontend-design",
    description: "Frontend design and UI/UX development tools",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/frontend-design",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "frontend"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/frontend-design/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-theme-factory",
    name: "theme-factory",
    description: "Style artifacts with professional themes or generate custom themes",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/theme-factory",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "theme"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/theme-factory/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-web-artifacts-builder",
    name: "web-artifacts-builder",
    description: "Build complex HTML artifacts with React and Tailwind",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/web-artifacts-builder",
    stars: 1500,
    category: "dev-tools",
    tags: ["anthropics", "official", "web"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/web-artifacts-builder/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-slack-gif-creator",
    name: "slack-gif-creator",
    description: "Create animated GIFs optimized for Slack size constraints",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/slack-gif-creator",
    stars: 1500,
    category: "communication",
    tags: ["anthropics", "official", "slack"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/slack-gif-creator/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-internal-comms",
    name: "internal-comms",
    description: "Write status reports, newsletters, and FAQs",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/internal-comms",
    stars: 1500,
    category: "content",
    tags: ["anthropics", "official", "writing"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/internal-comms/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "anthropics-brand-guidelines",
    name: "brand-guidelines",
    description: "Apply Anthropic's brand colors and typography to artifacts",
    author: "anthropics",
    repo_url: "https://github.com/anthropics/skills/tree/main/skills/brand-guidelines",
    stars: 1500,
    category: "design",
    tags: ["anthropics", "official", "brand"],
    skill_md_url: "https://github.com/anthropics/skills/blob/main/skills/brand-guidelines/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Vercel Skills (8) ==========
  {
    id: "vercel-react-best-practices",
    name: "react-best-practices",
    description: "React best practices and patterns from Vercel",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-best-practices",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "react", "best-practices"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-next-best-practices",
    name: "next-best-practices",
    description: "Next.js best practices and recommended patterns",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/next-skills/tree/main/skills/next-best-practices",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "nextjs", "best-practices"],
    skill_md_url: "https://github.com/vercel-labs/next-skills/blob/main/skills/next-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-web-design-guidelines",
    name: "web-design-guidelines",
    description: "Web design guidelines and standards from Vercel",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/web-design-guidelines",
    stars: 800,
    category: "design",
    tags: ["vercel", "design", "web"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/web-design-guidelines/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-composition-patterns",
    name: "composition-patterns",
    description: "React component composition and reusable patterns",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/composition-patterns",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "react", "patterns"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/composition-patterns/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-next-upgrade",
    name: "next-upgrade",
    description: "Upgrade Next.js projects to newer versions",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/next-skills/tree/main/skills/next-upgrade",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "nextjs", "upgrade"],
    skill_md_url: "https://github.com/vercel-labs/next-skills/blob/main/skills/next-upgrade/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "vercel-react-native-skills",
    name: "react-native-skills",
    description: "React Native best practices and performance guidelines",
    author: "vercel-labs",
    repo_url: "https://github.com/vercel-labs/agent-skills/tree/main/skills/react-native-skills",
    stars: 800,
    category: "dev-tools",
    tags: ["vercel", "react-native", "mobile"],
    skill_md_url: "https://github.com/vercel-labs/agent-skills/blob/main/skills/react-native-skills/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Cloudflare Skills (7) ==========
  {
    id: "cloudflare-wrangler",
    name: "wrangler",
    description: "Deploy and manage Workers, KV, R2, D1, Vectorize, Queues, Workflows",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/wrangler",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "workers", "deploy"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/wrangler/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "cloudflare-durable-objects",
    name: "durable-objects",
    description: "Stateful coordination with RPC, SQLite, and WebSockets",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/durable-objects",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "durable-objects", "state"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/durable-objects/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "cloudflare-agents-sdk",
    name: "agents-sdk",
    description: "Build stateful AI agents with scheduling, RPC, and MCP servers",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/agents-sdk",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "agents", "ai"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/agents-sdk/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "cloudflare-web-perf",
    name: "web-perf",
    description: "Audit Core Web Vitals and render-blocking resources",
    author: "cloudflare",
    repo_url: "https://github.com/cloudflare/skills/tree/main/skills/web-perf",
    stars: 600,
    category: "dev-tools",
    tags: ["cloudflare", "performance", "web"],
    skill_md_url: "https://github.com/cloudflare/skills/blob/main/skills/web-perf/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Supabase Skills ==========
  {
    id: "supabase-postgres-best-practices",
    name: "postgres-best-practices",
    description: "PostgreSQL best practices for Supabase",
    author: "supabase",
    repo_url: "https://github.com/supabase/agent-skills/tree/main/skills/supabase-postgres-best-practices",
    stars: 500,
    category: "data",
    tags: ["supabase", "postgres", "database"],
    skill_md_url: "https://github.com/supabase/agent-skills/blob/main/skills/supabase-postgres-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Stripe Skills ==========
  {
    id: "stripe-best-practices",
    name: "stripe-best-practices",
    description: "Best practices for building Stripe integrations",
    author: "stripe",
    repo_url: "https://github.com/stripe/ai/tree/main/skills/stripe-best-practices",
    stars: 400,
    category: "dev-tools",
    tags: ["stripe", "payments", "integration"],
    skill_md_url: "https://github.com/stripe/ai/blob/main/skills/stripe-best-practices/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "stripe-upgrade",
    name: "upgrade-stripe",
    description: "Upgrade Stripe SDK and API versions",
    author: "stripe",
    repo_url: "https://github.com/stripe/ai/tree/main/skills/upgrade-stripe",
    stars: 400,
    category: "dev-tools",
    tags: ["stripe", "upgrade", "sdk"],
    skill_md_url: "https://github.com/stripe/ai/blob/main/skills/upgrade-stripe/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== HuggingFace Skills (8) ==========
  {
    id: "huggingface-cli",
    name: "hugging-face-cli",
    description: "HF Hub CLI for models, datasets, repos, and compute jobs",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-cli",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "cli"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-cli/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-model-trainer",
    name: "hugging-face-model-trainer",
    description: "Train models with TRL: SFT, DPO, GRPO, GGUF conversion",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-model-trainer",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "training"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-model-trainer/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-datasets",
    name: "hugging-face-datasets",
    description: "Create and manage datasets with configs and SQL querying",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-datasets",
    stars: 350,
    category: "data",
    tags: ["huggingface", "ml", "datasets"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-datasets/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "huggingface-evaluation",
    name: "hugging-face-evaluation",
    description: "Model evaluation with vLLM/lighteval and eval tables",
    author: "huggingface",
    repo_url: "https://github.com/huggingface/skills/tree/main/skills/hugging-face-evaluation",
    stars: 350,
    category: "dev-tools",
    tags: ["huggingface", "ml", "evaluation"],
    skill_md_url: "https://github.com/huggingface/skills/blob/main/skills/hugging-face-evaluation/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Google Labs Skills (6) ==========
  {
    id: "google-shadcn-ui",
    name: "shadcn-ui",
    description: "Build UI components with shadcn/ui",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/shadcn-ui",
    stars: 300,
    category: "design",
    tags: ["google", "ui", "shadcn"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/shadcn-ui/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "google-react-components",
    name: "react-components",
    description: "Stitch to React components conversion",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/react-components",
    stars: 300,
    category: "design",
    tags: ["google", "react", "components"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/react-components/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "google-remotion",
    name: "remotion",
    description: "Generate walkthrough videos from Stitch app designs",
    author: "google-labs-code",
    repo_url: "https://github.com/google-labs-code/stitch-skills/tree/main/skills/remotion",
    stars: 300,
    category: "content",
    tags: ["google", "video", "remotion"],
    skill_md_url: "https://github.com/google-labs-code/stitch-skills/blob/main/skills/remotion/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Expo Skills (3) ==========
  {
    id: "expo-app-design",
    name: "expo-app-design",
    description: "Design Expo mobile applications",
    author: "expo",
    repo_url: "https://github.com/expo/skills/tree/main/plugins/expo-app-design",
    stars: 250,
    category: "design",
    tags: ["expo", "mobile", "react-native"],
    skill_md_url: "https://github.com/expo/skills/blob/main/plugins/expo-app-design/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "expo-deployment",
    name: "expo-deployment",
    description: "Deploy Expo apps to app stores",
    author: "expo",
    repo_url: "https://github.com/expo/skills/tree/main/plugins/expo-deployment",
    stars: 250,
    category: "automation",
    tags: ["expo", "deploy", "mobile"],
    skill_md_url: "https://github.com/expo/skills/blob/main/plugins/expo-deployment/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "expo-upgrading",
    name: "upgrading-expo",
    description: "Upgrade Expo SDK versions",
    author: "expo",
    repo_url: "https://github.com/expo/skills/tree/main/plugins/upgrading-expo",
    stars: 250,
    category: "dev-tools",
    tags: ["expo", "upgrade", "sdk"],
    skill_md_url: "https://github.com/expo/skills/blob/main/plugins/upgrading-expo/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Trail of Bits Security Skills (5) ==========
  {
    id: "tob-static-analysis",
    name: "static-analysis",
    description: "Static analysis for security vulnerabilities",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/static-analysis",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "analysis", "audit"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/static-analysis/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-semgrep-rule-creator",
    name: "semgrep-rule-creator",
    description: "Create Semgrep rules for code analysis",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/semgrep-rule-creator",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "semgrep", "rules"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/semgrep-rule-creator/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "tob-property-based-testing",
    name: "property-based-testing",
    description: "Property-based testing for robust code",
    author: "trailofbits",
    repo_url: "https://github.com/trailofbits/skills/tree/main/plugins/property-based-testing",
    stars: 200,
    category: "dev-tools",
    tags: ["security", "testing", "fuzzing"],
    skill_md_url: "https://github.com/trailofbits/skills/blob/main/plugins/property-based-testing/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },

  // ========== Community High-Quality Skills ==========
  {
    id: "alirezarezvani-brainstorm",
    name: "brainstorm",
    description: "Structured brainstorming and idea generation",
    author: "alirezarezvani",
    repo_url: "https://github.com/alirezarezvani/claude-skills",
    stars: 1892,
    category: "productivity",
    tags: ["brainstorm", "planning", "ideas"],
    skill_md_url: "https://github.com/alirezarezvani/claude-skills/blob/main/skills/brainstorm/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "timescale-pg-aiguide",
    name: "pg-aiguide",
    description: "PostgreSQL AI guide for database optimization",
    author: "timescale",
    repo_url: "https://github.com/timescale/pg-aiguide",
    stars: 1553,
    category: "data",
    tags: ["postgres", "ai", "database"],
    skill_md_url: "https://github.com/timescale/pg-aiguide/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "antonbabenko-terraform",
    name: "terraform-skill",
    description: "Terraform infrastructure as code best practices",
    author: "antonbabenko",
    repo_url: "https://github.com/antonbabenko/terraform-skill",
    stars: 1124,
    category: "automation",
    tags: ["terraform", "iac", "devops"],
    skill_md_url: "https://github.com/antonbabenko/terraform-skill/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
  {
    id: "addyosmani-web-quality",
    name: "web-quality-skills",
    description: "Web quality and performance best practices by Addy Osmani",
    author: "addyosmani",
    repo_url: "https://github.com/addyosmani/web-quality-skills",
    stars: 564,
    category: "dev-tools",
    tags: ["web", "performance", "quality"],
    skill_md_url: "https://github.com/addyosmani/web-quality-skills/blob/main/SKILL.md",
    created_at: "2024-01-01",
    updated_at: "2024-12-01",
  },
];
